name: Atualizar Header Message

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:  # Permite execução manual
  push:
    paths:
      - 'aniversariantes.json'
      - 'ferias.json'

jobs:
  update-header:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Executar script
        run: python generate_header_message.py
        
      - name: Commit e push das alterações
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add header_message.html
          git commit -m "Atualiza mensagem do header [automated]" || echo "Sem alterações para commit"
          git push
